---

#This configuration makes the loopback interfaces routable

- hosts: R1
  gather_facts: false

  tasks:
    - name: Configure interface settings
      cisco.ios.ios_config:
        lines:
        - ip ospf network point-to-point
        parents: interface Loopback1

- hosts: routers
  gather_facts: false
  tasks:
    - name: Configure interface settings
      cisco.ios.ios_config:
        lines:
        - ip ospf network point-to-point
        parents: interface Loopback0
        

...

