---

#This file configures a Gre Tunnel between Routers 3 and 4

- hosts: R3
  gather_facts: false

  tasks:
    - name: GRE Tunnel Configuration on R3
      cisco.ios.ios_config:
        lines:
        - ip address 10.10.10.1 255.255.255.252
        - tunnel source 192.168.6.1
        - tunnel destination 192.168.6.2
        parents: interface Tunnel1

- hosts: R4
  gather_facts: false
  tasks:
    - name: GRE Tunnel Configuration on R4
      cisco.ios.ios_config:
        lines:
        - ip address 10.10.10.2 255.255.255.252
        - tunnel source 192.168.6.2
        - tunnel destination 192.168.6.1
        parents: interface Tunnel2
        
...



