---

#This playbook configures the loopback interfaces on each of the routers

 - hosts: R1
   gather_facts: false
 
   tasks:
    - name: Loopback Interface Creation & IP Address Configuration 
      cisco.ios.ios_l3_interfaces:
       config:
       - name: Loopback0
         ipv4:
         - address: 192.168.10.1 255.255.255.0

       - name: Loopback1
         ipv4:
         - address: 192.168.20.1 255.255.255.0

       state: merged

 - hosts: R2
   gather_facts: false
   
   tasks:
   - name: Loopback Interface Creation & IP Address Configuration 
     cisco.ios.ios_l3_interfaces:
      config:
      - name: Loopback0
        ipv4:
        - address: 192.168.30.1 255.255.255.0
      - name: Loopback1
        ipv4:
        - address: 192.168.40.1 255.255.255.0

      state: merged

 - hosts: R3
   gather_facts: false
   
   tasks:
   - name: Loopback Interface Creation & IP Address Configuration 
     cisco.ios.ios_l3_interfaces:
      config:
      - name: Loopback0
        ipv4:
        - address: 192.168.50.1 255.255.255.0
      - name: Loopback1
        ipv4:
        - address: 192.168.60.1 255.255.255.0
        

      state: merged

 - hosts: R4
   gather_facts: false
   
   tasks:
    - name: Loopback Interface Creation & IP Address Configuration 
      cisco.ios.ios_l3_interfaces:
       config:
       - name: Loopback0
         ipv4:
         - address: 192.168.70.1 255.255.255.0
       - name: Loopback1
         ipv4:
         - address: 192.168.80.1 255.255.255.0
       
       state: merged



  
...
