---


- hosts: R1

  tasks:
   - name: Creating Loopback Interfaces & Configuring IPv4 and IPv6 Addresses on Them 
     cisco.ios.ios_l3_interfaces:
      config:
      - name: Loopback0
        ipv4:
        - address: 192.168.6.1/24
        ipv6:
        - address: 2001:DB8:CAFE:6::/64
      - name: Loopback1
        ipv4:
        - address: 192.168.0.1/24
        ipv6:
        - address: 2001:DB8:CAFE:1::/64
      state: replaced

- hosts: R2

  tasks:
  - name: Creating Loopback Interfaces & Configuring IPv4 and IPv6 Addresses on Them
    cisco.ios.ios_l3_interfaces:
     config:
     - name: Loopback0
       ipv4:
       - address: 192.168.3.1/24
       ipv6:
       - address: 2001:DB8:CAFE:3::/64
     state: replaced


- hosts: R3

  tasks:
  - name: Creating Loopback Interfaces & Configuring IPv4 and IPv6 Addresses on Them
    cisco.ios.ios_l3_interfaces:
     config:
     - name: Loopback0
       ipv4:
       - address: 192.168.5.1/24
       ipv6:
       - address: 2001:DB8:CAFE:5::/64
     state: replaced

- hosts: R4

  tasks:
  - name: Creating Loopback Interfaces & Configuring IPv4 and IPv6 Addresses on Them
    cisco.ios.ios_l3_interfaces:
     config:
     - name: Loopback0
       ipv4:
       - address: 192.168.99.1/24
       ipv6:
       - address: 2001:DB8:99:1::/64
     state: replaced
  
...
