---


- hosts: R2

  tasks:
   - name: Begin OSPF Interface configurations for R2
     cisco.ios.ios_ospf_interfaces:
      config:
       - name: GigabitEthernet0/2
         address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0
            adjacency: true
            dead_interval:
              time: 60
            network:
              broadcast: true
            resync_timeout: 10
            
       - name: Loopback0
         address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0
            adjacency: true
            dead_interval:
              time: 60
            network:
              broadcast: true
            resync_timeout: 10
      state: merged


- hosts: R3

  tasks:
   - name: Begin OSPF Interface configurations for R3
     cisco.ios.ios_ospf_interfaces:
      config:
       - name: GigabitEthernet0/1
         address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0
            adjacency: true
            dead_interval:
              time: 60
            network:
              broadcast: true
            resync_timeout: 10
       - name: Loopback0
         address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0
            adjacency: true
            dead_interval:
              time: 60
            network:
              broadcast: true
            resync_timeout: 10
       - name: GigabitEthernet0/0
         address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0
            adjacency: true
            dead_interval:
              time: 60
            network:
              broadcast: true
            resync_timeout: 10
                 
      state: merged












