---
- hosts: R2
  gather_facts: false

  tasks:
  - name: Configure OSPF on R2
    cisco.ios.ios_ospfv2:
       config:
        processes:
        - process_id: 1
          network:
           -  address: 192.168.3.0
              wildcard_bits: 0.0.0.255
              area: '1'
           -  address: 192.168.4.0
              wildcard_bits: 0.0.0.3
              area: '1'
       state: replaced


- hosts: R3
  gather_facts: false
  tasks:
  - name: Configure OSPF on R3
    cisco.ios.ios_ospfv2:
      config:
        processes:
        - process_id: 1
          network:
           -  address: 10.10.10.0
              wildcard_bits: 0.0.0.3
              area: '0'
           -  address: 192.168.4.0
              wildcard_bits: 0.0.0.3
              area: '1'
           -  address: 192.168.5.0
              wildcard_bits: 0.0.0.255
              area: '1'
           
        
      state: replaced

- hosts: R4
  gather_facts: false
  tasks:
  - name: Configure OSPF on R4 for Inter-Area Routing
    cisco.ios.ios_ospfv2:
      config:
        processes:
        - process_id: 1
          network:
           -  address: 192.168.99.0
              wildcard_bits: 0.0.0.255
              area: '2'
           -  address: 10.10.10.0
              wildcard_bits: 0.0.0.3
              area: '0'
           
        
      state: replaced






