
---
- hosts: R2
  tasks:
   - name: reboot ios device
     ios_command:
        command: reload
        prompt:
         - Save?
         - confirm
        answer:
         - y
         - y

   - name: reset the connection
     meta: reset_connection

   - name: Wait for the network device to reload
     wait_for_connection:
     delay: 2   
